name: Sync Latest Release   # 同步最新发布

on:
  schedule:
    - cron: '0 * * * *'  # 每小时运行
  workflow_dispatch:      # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      NO_UPDATE: false
      RELEASE_TAG: ''
      DOWNLOAD_URL: ''
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3        # 检出代码库
        
      - name: Get latest release info
        id: release
        run: |
          # 获取最新发布信息
          RELEASE_INFO=$(curl -s https://api.github.com/repos/Zephyruso/zashboard/releases/latest)
          echo "RELEASE_TAG=$(echo $RELEASE_INFO | jq -r .tag_name)" >> $GITHUB_ENV
          echo "DOWNLOAD_URL=$(echo $RELEASE_INFO | jq -r '.assets[] | select(.name=="dist.zip") | .browser_download_url')" >> $GITHUB_ENV
          
      - name: Check last processed version
        id: check_version
        run: |
          # 检查上一次处理的版本
          if [ ! -f README.md ] || ! grep -q "<!-- RELEASE_TAG -->" README.md; then
            echo "当前版本: <!-- RELEASE_TAG -->v0.0.0<!-- /RELEASE_TAG -->" >> README.md
          fi
          LAST_VERSION=$(sed -n 's/.*<!-- RELEASE_TAG -->\(.*\)<!-- \/RELEASE_TAG -->/\1/p' README.md)
          echo "LAST_VERSION=$LAST_VERSION" >> $GITHUB_ENV
          if [ "$LAST_VERSION" == "${{ env.RELEASE_TAG }}" ]; then
            echo "NO_UPDATE=true" >> $GITHUB_ENV
          fi
          
      - name: Download and extract release
        if: env.NO_UPDATE != 'true'
        run: |
          # 下载并解压最新发布包
          curl -L "${{ env.DOWNLOAD_URL }}" -o dist.zip
          mkdir -p temp_dist
          unzip dist.zip -d temp_dist
          
      - name: Clean existing files
        if: env.NO_UPDATE != 'true'
        run: |
          # 创建需要保留的文件列表
          echo ".github/" > preserve.txt
          echo "README.md" >> preserve.txt
          
          # 删除除保留列表以外的文件
          find . -maxdepth 1 -type f ! -name "$(paste -sd '|' preserve.txt)" -delete
          find . -maxdepth 1 -type d ! -name ".*" ! -name "temp_dist" -exec rm -rf {} +
          
      - name: Move files to root
        if: env.NO_UPDATE != 'true'
        run: |
          # 将解压目录中的文件移动到仓库根目录
          mv temp_dist/dist/* .
          rm -rf temp_dist
          
      - name: Update version in README
        if: env.NO_UPDATE != 'true'
        run: |
          sed -i "s|<!-- RELEASE_TAG -->v[0-9.]*<!-- /RELEASE_TAG -->|<!-- RELEASE_TAG -->${{ env.RELEASE_TAG }}<!-- /RELEASE_TAG -->|" README.md
          sed -i "s|\[<!-- RELEASE_TAG -->v[0-9.]*<!-- /RELEASE_TAG -->\](https://github.com/Zephyruso/zashboard/releases)|[<!-- RELEASE_TAG -->${{ env.RELEASE_TAG }}<!-- /RELEASE_TAG -->](https://github.com/Zephyruso/zashboard/releases)|" README.md
          
      - name: Commit and push changes
        if: env.NO_UPDATE != 'true'
        run: |
          # 配置 Git 并提交更新
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "Sync latest release ${{ env.RELEASE_TAG }}"
          git push